project:
  type: website

website:
  title: "GIS Project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: proposal.qmd
        text: Project Proposal
      - text: "Methodology & Report"
        menu:
          - text: Project Report
            href: report.qmd
          - text: Methodology
            href: methodology.qmd
      - href: minutes.qmd
        text: Meeting Minutes
      - href: poster.qmd
        text: Poster
      - href: results_discuss.qmd
        text: Results & Discussion
      - href: lessons.qmd
        text: Lessons Learnt
      
    right:
      - href: about.qmd
        text: About
        
    tools:
    - icon: github
      href: https://github.com/wnyeo/GISProject



format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

