---
title: "Lessons Learnt"
format:
  html:
    toc: false
    page-layout: full
---

Throughout this project, our team has learnt the importance of documentation when doing projects. Doing up the documentation for analysis and meeting minutes for this project has allowed us to appreciate the importance of documentation in not just allowing for reproducibility, but also helping with troubleshooting. When we are not sure of details with previous analysis, we are able to make use of the documentation to recall and revisit the details. Documentation has also allowed everyone to be clear about the project, ensuring that the team is on the right track.

The second learning point was to conduct a cross check or validation with other sources to ensure that we are on the right track. This includes our clarifications with Prof Kam and also with online sources. For this project, we referenced flood trace and flood area data from Copernicus Emergency Management Service - Mapping to better understand what were the areas of flooding.

Third, contextual research is crucial before starting on a project. Contextual research on the topic or area has allowed the team to gain a better understanding of what happened and decide on the methodologies. We are also able to better interpret results with contextual understanding.

Lastly, it is important to know the purpose of a type of analysis before starting on it. This can provide more direction and allow the analysis as well as the recommendations to be more targeted. For example, before starting on our analysis, we clarified the use cases of land cover change analysis with Prof. Kam before starting on it. In this case it was to identify which land cover types were affected the most. This helped us decide on what land cover types could represent flood impact (Bare land and Water Body).

We would like to thank Prof. Kam for his continued guidance for this project.
