---
title: "Meeting Minutes"
format:
  html:
    toc: false
---

+----------------------------------------------+-------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+
| Time                                         | Agenda                                                                        | Minutes                                                                                                                                                                                                                                                      | Action Items                                                                             |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | \*Decisions are highlighted                                                                                                                                                                                                                                  |                                                                                          |
+==============================================+===============================================================================+==============================================================================================================================================================================================================================================================+==========================================================================================+
| 9 October 2023, 1530 - 1630 hrs              | Internal Team Meeting                                                         | 1.  Theme and analysis plan:                                                                                                                                                                                                                                 | To book a consultation slot with Prof. Kam                                               |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
| (In person)                                  | 1.  Decide on theme and analysis plan                                         |     1.  Theme 1                                                                                                                                                                                                                                              | Some reading and literature review of the application                                    |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              | 2.  List down questions we have for prof                                      |         1.  Looks more interesting but to check with Prof about our analysis plan to see feasibility of plan and if our understanding of the Theme is correct                                                                                                |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              | 3.  Set and book consultation with Prof                                       |         2.  Analysis:                                                                                                                                                                                                                                        |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              | 4.  To do by next meeting                                                     |             1.  Choose two dates for comparison                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              | 5.  AOM                                                                       |             2.  Data compilation                                                                                                                                                                                                                             |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               |         3.  Questions                                                                                                                                                                                                                                        |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               |             1.  How to choose the two dates to compare the land use/land cover? Should we research the optimal dates? Is there a "best practice" method of choosing the two dates for comparison?                                                            |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               |             2.  How can we do the comparison                                                                                                                                                                                                                 |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               |                 1.  Like something similar to NDVI for different kinds of land use.                                                                                                                                                                          |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               |                 2.  Or some classification tool for satellite data                                                                                                                                                                                           |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               |             3.  Should we take into account the different types of flooding and the land use?                                                                                                                                                                |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               |                 1.  Eg: pluvial and fluvial flooding and land use                                                                                                                                                                                            |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               |     2.  Theme 2                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               |         1.  Somewhat like the Childcare Center accessibility analysis                                                                                                                                                                                        |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               |         2.  Analysis:                                                                                                                                                                                                                                        |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               |             1.  Approach would be like the childcare accessibility for Punggol area                                                                                                                                                                          |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               |             2.  Finding out distance between residential areas and medical and evacuation areas                                                                                                                                                              |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               |     3.  Theme 3                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               |         1.  GIS and remote sensing data → remote sensing data aspect would be the satellite images, QGIS analysis comes in for recovery planning, distance to evacuation centres                                                                             |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               |         2.  Analysis:                                                                                                                                                                                                                                        |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               |             1.  Possible dataset: <https://data.humdata.org/dataset/buildings-footprint-floods-derna-libya>                                                                                                                                                  |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               |         3.  Question:                                                                                                                                                                                                                                        |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               |             1.  What kind of loss (areas impacted more by flood?)                                                                                                                                                                                            |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               |             2.  Is the data on flood impact on buildings relevant to this theme?                                                                                                                                                                             |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | <!-- -->                                                                                                                                                                                                                                                     |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | 2.  General Questions                                                                                                                                                                                                                                        |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | -   Is there a format for the meeting minutes                                                                                                                                                                                                                |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | -   Under methodology what is required?                                                                                                                                                                                                                      |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | 3.  Consultation Datetime: Friday, 9 am                                                                                                                                                                                                                      |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | 4.  Some reading and literature review of the application                                                                                                                                                                                                    |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | 5.  Internal Team meetings would be on every Tuesday afternoon                                                                                                                                                                                               |                                                                                          |
+----------------------------------------------+-------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+
| 13 October 2023, 0900 - 0930 hrs (Zoom)      | Consultation with Prof                                                        | **Prof's explanation for Theme 1:**                                                                                                                                                                                                                          | Select Theme for Analysis and draft out analysis plan                                    |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | This week hands on not enough                                                                                                                                                                                                                                |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | -   Extract data                                                                                                                                                                                                                                             |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | -   Image enhancement                                                                                                                                                                                                                                        |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | -   Derive composite image                                                                                                                                                                                                                                   |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | -   Need also next week lesson                                                                                                                                                                                                                               |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | Idea is - apply appropriate methods to do land classification                                                                                                                                                                                                |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | -   When doing classification - label to different land cover type                                                                                                                                                                                           |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               |     -   Refer to hands on for next week - do sampling                                                                                                                                                                                                        |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               |         -   refer to the carte composite layer, identify to confirm the land use                                                                                                                                                                             |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               |         -   Use it as training data to classify entire image                                                                                                                                                                                                 |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               |     -   Refer to colour composite map - true and false (main source)                                                                                                                                                                                         |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               |         -   get different land cover types with various colour composite maps                                                                                                                                                                                |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               |         -   Use other resources - higher res data/ open street map                                                                                                                                                                                           |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | On choosing the different dates                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | -   before and after the flood                                                                                                                                                                                                                               |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | <!-- -->                                                                                                                                                                                                                                                     |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | -   As close as possible to the event                                                                                                                                                                                                                        |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | On different types of flooding                                                                                                                                                                                                                               |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | -   Should be able to detect using satellite imagery                                                                                                                                                                                                         |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | -   This particular flooding - cause by 2 factors                                                                                                                                                                                                            |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               |     -   Natural - big storm                                                                                                                                                                                                                                  |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               |         -   But there is a dam there to regulate the area, but 2 of the dam collapsed, cannot regulate water                                                                                                                                                 |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               |     -   Dam collapse                                                                                                                                                                                                                                         |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | Use case for this kind of analysis?                                                                                                                                                                                                                          |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | -   Quantify and delineate extend of flood and dam failure from change detection                                                                                                                                                                             |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               |     -   How far the flood affect the area - not the entire city                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               |     -   Extent of the impact is also different                                                                                                                                                                                                               |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               |         -   Eg: location near rivers and near dams - greater impact as compared to those further                                                                                                                                                             |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               |     -   Know the infrastructure affected - roads, buildings, etc.                                                                                                                                                                                            |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               |     -   Assess level of damages - use this as a reference for mitigation and prevention                                                                                                                                                                      |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | **Prof's explanation for Theme 3:**                                                                                                                                                                                                                          |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | What kind of loss (areas impacted more by flood?)                                                                                                                                                                                                            |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | -   Referring to the data sources provided:                                                                                                                                                                                                                  |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               |     -   Combine the UN libya data with satellite data                                                                                                                                                                                                        |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               |         -   See how many facilities that can still be accessed? (E.g: healthcare facilities, roads, etc)                                                                                                                                                     |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | -   All kinds of losses                                                                                                                                                                                                                                      |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               |     -   Quantify the type of losses                                                                                                                                                                                                                          |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               |     -   Eg: close to 500 km of roads network severely affected                                                                                                                                                                                               |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               |         -   Help engineers/ city council to estimate repair needed (the extent)                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | Is the data on flood impact on buildings relevant to this theme?                                                                                                                                                                                             |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | -   After the data is combined - eg financial services with satellite                                                                                                                                                                                        |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               |     -   Detect how financial services are affected                                                                                                                                                                                                           |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | **A question raised on the difference between Theme 1 and 3:**                                                                                                                                                                                               |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | -   1: focus on satellite imagery, classification and machine learning to see difference in change detection                                                                                                                                                 |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               |     -   Make use of image detection to see changes.                                                                                                                                                                                                          |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | -   3: one change detection to delineate flood loss                                                                                                                                                                                                          |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               |     -   More fine grained to see how the flood has affected.                                                                                                                                                                                                 |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               |     -   More on impact assessments                                                                                                                                                                                                                           |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | **Prof's response to General Questions:**                                                                                                                                                                                                                    |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | Question: Is there a format for the meeting minutes?                                                                                                                                                                                                         |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | -   Current one is good enough                                                                                                                                                                                                                               |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | -   Content more important - document discussion in greater detail                                                                                                                                                                                           |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               |     -   Who asked what and rationale for asking                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | Question: Under methodology what is required (General walkthrough or step by step)?                                                                                                                                                                          |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | -   Some have high level discussion - with separate tab/ word doc to describe steps (like take home exercise)                                                                                                                                                |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | -   Project - leeway to be creative - learning experience from take home                                                                                                                                                                                     |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | -   Important to provide detail and reproducible documentation of process gone through                                                                                                                                                                       |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               |     -   People can reproduce                                                                                                                                                                                                                                 |                                                                                          |
+----------------------------------------------+-------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+
| 17 October 2023, 1400 hrs                    | Internal Team Meeting                                                         | 1.  Project timeline is good                                                                                                                                                                                                                                 | Search for data on Landsat8                                                              |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
| (zoom)                                       | 1.  Review Project timeline                                                   | 2.  Analysis plan is good                                                                                                                                                                                                                                    | Assemble data and do preliminary analysis                                                |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              | 2.  Review analysis plan                                                      | 3.  Decided on meeting on Zoom, on Thursday, 18 october, 9am to Consult Prof. Kam                                                                                                                                                                            |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              | 3.  Schedule meeting with Prof                                                | **Questions for Prof:**                                                                                                                                                                                                                                      |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              | 4.  Compile questions for Prof                                                | -   Suitability of using data from 22 October for comparison (instead of data from just after the flood)                                                                                                                                                     |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              | 5.  Any other matters                                                         |     -   Due to lack of clear data                                                                                                                                                                                                                            |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | -   How much test data is typically appropriate? How to decide?                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | -   Pros and cons of grouping in the same meta class/ separate?                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | -   Any recommendations for other classification tools to use?                                                                                                                                                                                               |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | -   On choosing the training data/ testing data - which layer (tcc/ fcc) to use?                                                                                                                                                                             |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               |     -   Before or after                                                                                                                                                                                                                                      |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | 4.  Other matters                                                                                                                                                                                                                                            |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | <!-- -->                                                                                                                                                                                                                                                     |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | 1.  On decision of using either Landsat8 or Sentinel2 data: use the source with clear view and least cloud cover                                                                                                                                             |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | 2.  Decided on classes to use for classification:                                                                                                                                                                                                            |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | -   Water body                                                                                                                                                                                                                                               |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | -   Bare land                                                                                                                                                                                                                                                |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | -   Build up areas                                                                                                                                                                                                                                           |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               |     -   High                                                                                                                                                                                                                                                 |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               |     -   low                                                                                                                                                                                                                                                  |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | -   Vegetation                                                                                                                                                                                                                                               |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | -   Impervious surfaces                                                                                                                                                                                                                                      |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | 3.  There will be an alignment of training dataset used after finalising the data                                                                                                                                                                            |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | 4.  On the project website:                                                                                                                                                                                                                                  |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               |     1.  The step-by-step guide will be a link to the document                                                                                                                                                                                                |                                                                                          |
+----------------------------------------------+-------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+
| 19 October 2023, 0900 - 0930 hrs (Zoom)      | Consultation with Prof. Kam                                                   | **Question on the suitability of using data on 22 September for the "after" comparison, instead of data from just after the flood, due to lack of clear data:**                                                                                              | Search again for suitable post flood data                                                |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              | 1.  Ask Prof. Kam questions                                                   | -   To check data for 12 and 13 September on Sentinel (should not have high cloud cover)                                                                                                                                                                     |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | **How much test data is typically appropriate? How to decide?**                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | -   Has more to do with the spread (should get a variety for each class)                                                                                                                                                                                     |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | -   For each land cover type (class, not meta class), at least 30 pixels (in total)                                                                                                                                                                          |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | **Pros and cons of grouping in the same meta class/ separate?**                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | -   Can group classes under one meta class                                                                                                                                                                                                                   |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | **Any recommendations for other classification tools to use?**                                                                                                                                                                                               |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | -   Those shared in class should be good enough                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | -   Usually GIS community uses statistical methods but are moving towards ML techniques                                                                                                                                                                      |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | -   Usually use maximum likelihood under statistical methods                                                                                                                                                                                                 |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | -   SCP only provides random forest in terms of ML techniques                                                                                                                                                                                                |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | -   Can search for remote sensing under plugins and we will see a list                                                                                                                                                                                       |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | -   Can explore Orfeo                                                                                                                                                                                                                                        |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | **On choosing the training data/ testing data - which layer (TCC/ FCC) to use?**                                                                                                                                                                             |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | -   Training data should be different before and after                                                                                                                                                                                                       |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | -   Different samples from same location but categorised to different land use types                                                                                                                                                                         |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | -   For after flood: severely damaged, moderately damaged, not damaged                                                                                                                                                                                       |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               |     -   Use humanitarian data source (ground truth) to find                                                                                                                                                                                                  |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | **How to determine the extent of the flood**                                                                                                                                                                                                                 |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | -   Depends on the classification map                                                                                                                                                                                                                        |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | **Purpose of PCA**                                                                                                                                                                                                                                           |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | -   A form of transformation such that the data is not correlated                                                                                                                                                                                            |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | -   Used to deal with highly correlated data (e.g. infrared and red light when there is high vegetation)                                                                                                                                                     |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | -   Maximum likelihood method isn't suitable when dealing with highly correlated data                                                                                                                                                                        |                                                                                          |
+----------------------------------------------+-------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+
| 21 October 2023, 1500 - 1700 hrs (In person) | Internal Team Meeting                                                         | 1.  Other than SCP for maximum likelihood and minimum distance, look into Dzetsaka Plugin                                                                                                                                                                    | Perform Classification on Pre-Flood and Post-Flood raster data using SCP and other tools |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              | Agenda                                                                        |     1.  Reason: Dzetsaka provides more options for different algorithms to classify raster data (SVM, Random Forest, KNN, Gaussian Mixture Model)                                                                                                            | To share classification results with each other                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              | 1.  Decide on classification Tools and algorithms to explore                  | 2.  For both Pre and Post floods raster layers:                                                                                                                                                                                                              | Decide on classification tool/ plugin to use                                             |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              | 2.  Go through general steps for analysis (the step by step guide)            | Select classes - same for training and testing                                                                                                                                                                                                               |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              | 3.  Update classes                                                            | Training                                                                                                                                                                                                                                                     |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | -   Select areas, add training samples for each land cover type                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | -   Check ROI signature                                                                                                                                                                                                                                      |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | -   Run SCP Classification on 2 Algorithm: Minimum Distance and Maximum Likelihood                                                                                                                                                                           |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | -   Run Random forest classification with Dzetsaka                                                                                                                                                                                                           |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | Testing                                                                                                                                                                                                                                                      |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | -   Add testing samples for each land cover type                                                                                                                                                                                                             |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | -   Calculate accuracy for the different algorithms using the same test samples in previous step - with SCP                                                                                                                                                  |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | Select better Algorithm                                                                                                                                                                                                                                      |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | Final evaluation of classification model                                                                                                                                                                                                                     |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | 3.  Updated classes                                                                                                                                                                                                                                          |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | -   Built-up area                                                                                                                                                                                                                                            |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | -   Bare land                                                                                                                                                                                                                                                |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | -   Impervious surfaces                                                                                                                                                                                                                                      |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | -   Water body                                                                                                                                                                                                                                               |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | -   Vegetation                                                                                                                                                                                                                                               |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | -   Cloud                                                                                                                                                                                                                                                    |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | -   Cloud shadow                                                                                                                                                                                                                                             |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | Added new classes for cloud and cloud shadow to account for the cloud cover and cloud shadow present in post flood dataset                                                                                                                                   |                                                                                          |
+----------------------------------------------+-------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+
| 30 October 2023, 1630 - 1700 hrs             | Consultation with Prof. Kam                                                   | Addressing Cloud Cover for GeoEye data:                                                                                                                                                                                                                      | Research how to split multiband images into individual bands                             |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
| (Zoom)                                       | 1.  Ask about addressing Cloud Cover for Geoeye data                          | -   Try Random Forest for Geoeye data classification if Max Likelihood is not working                                                                                                                                                                        | Remove band 4 / any bands without different min and max between bands                    |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              | 2.  Ask about Bands used for colour composite maps (Sentinel data and Geoeye) | -   SCP Cloud Masking should work for all data types                                                                                                                                                                                                         | Perform classification                                                                   |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              | 3.  Ask about inability to see spectral signature plot after selecting ROIs   | -   Check Spectral Plot to see min and max values for each Band \> Band 4 seems to have no difference between classes, so remove it                                                                                                                          |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               |     -   To research how to (currently getting error message: Unable to remove bands in a multiband image)                                                                                                                                                    |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | -   To note that the resolution is different for Sentinel and GeoEye satellite data so it might affect the number of pixels classified as a class                                                                                                            |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | **Bands used for colour composite maps**                                                                                                                                                                                                                     |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | -   Brought up False Colour Composite issue when using bands 4-3-2 for False                                                                                                                                                                                 |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               |     -   Prof. Kam's response: Not an issue! It really looks like that due to different land cover in Derna                                                                                                                                                   |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | -   Prof. Kam brought up observation that GeoEye Band 4 is noise                                                                                                                                                                                             |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               |     -   Tried removing Band 4 but unable to remove                                                                                                                                                                                                           |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | **Inability to see spectral signature plots after digitising ROIs:**                                                                                                                                                                                         |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | -   Wei Ni not able to see signature plot as the type is ROI instead of R&S in her ROI Signature list                                                                                                                                                        |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               |     -   Prof. Kam suspects that there is error with one band                                                                                                                                                                                                 |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               |     -   Suggested to split up bands and bring bands in one by one                                                                                                                                                                                            |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               |         -   QGIS has function to split multiband into single band                                                                                                                                                                                            |                                                                                          |
+----------------------------------------------+-------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+
| 3 November 2023                              | No meeting - decisions made offline                                           | -   Changed Pre-Flood and Post-Flood Raster data source to Maxar                                                                                                                                                                                             | Perform Classification using data from Maxar                                             |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               |     -   This is due to issues with Band 4 of the original GeoEye data from OpenArialMap and because Maxar provides raster maps for both Pre-Flood and Post-Flood, allowing us to standardise the resolution of the maps used for Land Cover Change Detection |                                                                                          |
+----------------------------------------------+-------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+
| 6 November 2023,                             | Internal Team Meeting                                                         | -   Conducted land use change detection on Xin Yi's laptop for the pre and post flood classification layer with the SCP plugin.                                                                                                                              | Create template for poster on canva                                                      |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
| 1600 - 1730 hrs                              | 1.  Perform Land use Change Detection using SCP                               | <!-- -->                                                                                                                                                                                                                                                     |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
| (In person)                                  | 2.  Draw insights from Land use Change Detection                              | -   After the analysis is conducted, decided to focus on changes to two land cover types of interest for Land Cover Change Detection:                                                                                                                        |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | 1.  Bare land                                                                                                                                                                                                                                                |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | 2.  Water body                                                                                                                                                                                                                                               |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | -   This is because land use changes to bare land and water bodies reflect areas of damage and flooding.                                                                                                                                                     |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | Insights from the land use change detection include:                                                                                                                                                                                                         |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | -   Areas near the dam are more damaged due to greater change to bare land                                                                                                                                                                                   |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
|                                              |                                                                               | -   Flooding present near the coast                                                                                                                                                                                                                          |                                                                                          |
+----------------------------------------------+-------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+
| 7 November 2023,                             | Internal Team Meeting                                                         | -   Decided on including the following sections in poster: Problem/ Motivation, Objectives, Approach, Insights and Recommendations, Limitations, Future Work                                                                                                 | Refine poster for submission and submit poster                                           |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
| 1200 - 1500 hrs                              | 1.  Completion of Project poster                                              | -   Poster completion on Canva                                                                                                                                                                                                                               |                                                                                          |
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
| (In person)                                  |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
+----------------------------------------------+-------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+
|                                              |                                                                               |                                                                                                                                                                                                                                                              |                                                                                          |
+----------------------------------------------+-------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+
